In [84]:
import pandas as pd

In [85]:
df=pd.read_csv("StudentsPerformance.csv")

In [86]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [87]:
df.shape

(1000, 8)

In [88]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [89]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [91]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [92]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [93]:
df.duplicated().sum()

np.int64(0)

In [94]:
Categorical_cols=["gender","race/ethnicity","parental level of education","lunch","test preparation course"]

In [95]:
Categorical_cols

['gender',
 'race/ethnicity',
 'parental level of education',
 'lunch',
 'test preparation course']

In [96]:
for cols in Categorical_cols:
    df[cols]=df[cols].astype(str).str.strip().str.lower()

In [97]:
df[cols]

0           none
1      completed
2           none
3           none
4           none
         ...
995    completed
996         none
997    completed
998    completed
999         none
Name: test preparation course, Length: 1000, dtype: object

In [98]:
score_cols=["math score","reading score","writing score"]

In [99]:
score_cols

['math score', 'reading score', 'writing score']

In [100]:
for cols in score_cols:
    mean=df[cols].mean()
    print("mean score:",mean)
    median=df[cols].median()
    print("median score:",median)
    mode=df[cols].mode()
    print("mode score:",mode)
    std=df[cols].std()
    print("std score:",std)
    Q1=df[cols].quantile(0.25)
    print("Q1 score:",Q1)
    Q3=df[cols].quantile(0.75)
    print("Q3 score:",Q3)

mean score: 66.089
median score: 66.0
mode score: 0    65
Name: math score, dtype: int64
std score: 15.163080096009468
Q1 score: 57.0
Q3 score: 77.0
mean score: 69.169
median score: 70.0
mode score: 0    72
Name: reading score, dtype: int64
std score: 14.60019193725222
Q1 score: 59.0
Q3 score: 79.0
mean score: 68.054
median score: 69.0
mode score: 0    74
Name: writing score, dtype: int64
std score: 15.195657010869642
Q1 score: 57.75
Q3 score: 79.0

In [101]:
print(df[score_cols].describe())

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [102]:
df["Total Marks"]=df[score_cols].sum(axis=1)

In [103]:
df["Percentage"]=(df["Total Marks"]/300)*100

In [104]:
print(df[score_cols+["Total Marks","Percentage"]])

     math score  reading score  writing score  Total Marks  Percentage
0            72             72             74          218   72.666667
1            69             90             88          247   82.333333
2            90             95             93          278   92.666667
3            47             57             44          148   49.333333
4            76             78             75          229   76.333333
..          ...            ...            ...          ...         ...
995          88             99             95          282   94.000000
996          62             55             55          172   57.333333
997          59             71             65          195   65.000000
998          68             78             77          223   74.333333
999          77             86             86          249   83.000000

[1000 rows x 5 columns]

In [105]:
performance=[]
for Percentage in df["Percentage"]:
    if Percentage>=90:
        performance.append("excellent")
    elif Percentage>=75:
        performance.append("very good")
    elif Percentage>=60:
        performance.append("good")
    elif Percentage>=50:
        performance.append("average")
    else:
        performance.append("need a improvment")
df["performance"]=performance
print(df[["Percentage","performance"]])

     Percentage        performance
0     72.666667               good
1     82.333333          very good
2     92.666667          excellent
3     49.333333  need a improvment
4     76.333333          very good
..          ...                ...
995   94.000000          excellent
996   57.333333            average
997   65.000000               good
998   74.333333               good
999   83.000000          very good

[1000 rows x 2 columns]

In [107]:
for col in["math score","reading score","writing score"]:
    
    Q1=df[col].quantile(0.25)
    Q3=df[col].quantile(0.75)
    
    IQR=Q3-Q1
    
    lower=Q1-1.5*IQR
    upper=Q3+1.5*IQR
    
    outliers=df[
        (df[col]<lower)|
        (df[col]>upper)
        ]

    print(outliers[col])

17     18
59      0
145    22
338    24
466    26
787    19
842    23
980     8
Name: math score, dtype: int64
59     17
76     26
211    28
327    23
596    24
980    24
Name: reading score, dtype: int64
59     10
76     22
327    19
596    15
980    23
Name: writing score, dtype: int64